name: MooManager
options:
  bundleIdPrefix: com.karnies
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
targets:
  MooManager:
    type: application
    platform: iOS
    sources:
      - path: MooManager
        excludes:
          - "**/*.xcassets"
    resources:
      - path: MooManager/Resources/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: MooManager/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.karnies.moomanager
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1"
